# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/pahmeyer/Documents/GitHub/gdx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/pahmeyer/Documents/GitHub/gdx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pahmeyer/Documents/GitHub/gdx/CMakeFiles /Users/pahmeyer/Documents/GitHub/gdx//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pahmeyer/Documents/GitHub/gdx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gdxcclib64

# Build rule for target.
gdxcclib64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gdxcclib64
.PHONY : gdxcclib64

# fast build rule for target.
gdxcclib64/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/build
.PHONY : gdxcclib64/fast

#=============================================================================
# Target rules for targets named gdxtest

# Build rule for target.
gdxtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gdxtest
.PHONY : gdxtest

# fast build rule for target.
gdxtest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/build
.PHONY : gdxtest/fast

#=============================================================================
# Target rules for targets named gdxwraptest

# Build rule for target.
gdxwraptest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gdxwraptest
.PHONY : gdxwraptest

# fast build rule for target.
gdxwraptest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxwraptest.dir/build.make CMakeFiles/gdxwraptest.dir/build
.PHONY : gdxwraptest/fast

#=============================================================================
# Target rules for targets named xp_example1

# Build rule for target.
xp_example1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xp_example1
.PHONY : xp_example1

# fast build rule for target.
xp_example1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/build
.PHONY : xp_example1/fast

#=============================================================================
# Target rules for targets named xp_example2

# Build rule for target.
xp_example2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xp_example2
.PHONY : xp_example2

# fast build rule for target.
xp_example2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/build
.PHONY : xp_example2/fast

generated/gdxcc.o: generated/gdxcc.c.o
.PHONY : generated/gdxcc.o

# target to build an object file
generated/gdxcc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxwraptest.dir/build.make CMakeFiles/gdxwraptest.dir/generated/gdxcc.c.o
.PHONY : generated/gdxcc.c.o

generated/gdxcc.i: generated/gdxcc.c.i
.PHONY : generated/gdxcc.i

# target to preprocess a source file
generated/gdxcc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxwraptest.dir/build.make CMakeFiles/gdxwraptest.dir/generated/gdxcc.c.i
.PHONY : generated/gdxcc.c.i

generated/gdxcc.s: generated/gdxcc.c.s
.PHONY : generated/gdxcc.s

# target to generate assembly for a file
generated/gdxcc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxwraptest.dir/build.make CMakeFiles/gdxwraptest.dir/generated/gdxcc.c.s
.PHONY : generated/gdxcc.c.s

generated/gdxcclib.o: generated/gdxcclib.cpp.o
.PHONY : generated/gdxcclib.o

# target to build an object file
generated/gdxcclib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/generated/gdxcclib.cpp.o
.PHONY : generated/gdxcclib.cpp.o

generated/gdxcclib.i: generated/gdxcclib.cpp.i
.PHONY : generated/gdxcclib.i

# target to preprocess a source file
generated/gdxcclib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/generated/gdxcclib.cpp.i
.PHONY : generated/gdxcclib.cpp.i

generated/gdxcclib.s: generated/gdxcclib.cpp.s
.PHONY : generated/gdxcclib.s

# target to generate assembly for a file
generated/gdxcclib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/generated/gdxcclib.cpp.s
.PHONY : generated/gdxcclib.cpp.s

generated/optcc.o: generated/optcc.c.o
.PHONY : generated/optcc.o

# target to build an object file
generated/optcc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/generated/optcc.c.o
.PHONY : generated/optcc.c.o

generated/optcc.i: generated/optcc.c.i
.PHONY : generated/optcc.i

# target to preprocess a source file
generated/optcc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/generated/optcc.c.i
.PHONY : generated/optcc.c.i

generated/optcc.s: generated/optcc.c.s
.PHONY : generated/optcc.s

# target to generate assembly for a file
generated/optcc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/generated/optcc.c.s
.PHONY : generated/optcc.c.s

src/examples/xp_example1.o: src/examples/xp_example1.cpp.o
.PHONY : src/examples/xp_example1.o

# target to build an object file
src/examples/xp_example1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/examples/xp_example1.cpp.o
.PHONY : src/examples/xp_example1.cpp.o

src/examples/xp_example1.i: src/examples/xp_example1.cpp.i
.PHONY : src/examples/xp_example1.i

# target to preprocess a source file
src/examples/xp_example1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/examples/xp_example1.cpp.i
.PHONY : src/examples/xp_example1.cpp.i

src/examples/xp_example1.s: src/examples/xp_example1.cpp.s
.PHONY : src/examples/xp_example1.s

# target to generate assembly for a file
src/examples/xp_example1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/examples/xp_example1.cpp.s
.PHONY : src/examples/xp_example1.cpp.s

src/examples/xp_example2.o: src/examples/xp_example2.cpp.o
.PHONY : src/examples/xp_example2.o

# target to build an object file
src/examples/xp_example2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/examples/xp_example2.cpp.o
.PHONY : src/examples/xp_example2.cpp.o

src/examples/xp_example2.i: src/examples/xp_example2.cpp.i
.PHONY : src/examples/xp_example2.i

# target to preprocess a source file
src/examples/xp_example2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/examples/xp_example2.cpp.i
.PHONY : src/examples/xp_example2.cpp.i

src/examples/xp_example2.s: src/examples/xp_example2.cpp.s
.PHONY : src/examples/xp_example2.s

# target to generate assembly for a file
src/examples/xp_example2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/examples/xp_example2.cpp.s
.PHONY : src/examples/xp_example2.cpp.s

src/gmsstrm.o: src/gmsstrm.cpp.o
.PHONY : src/gmsstrm.o

# target to build an object file
src/gmsstrm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/src/gmsstrm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/gmsstrm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/gmsstrm.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/gmsstrm.cpp.o
.PHONY : src/gmsstrm.cpp.o

src/gmsstrm.i: src/gmsstrm.cpp.i
.PHONY : src/gmsstrm.i

# target to preprocess a source file
src/gmsstrm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/src/gmsstrm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/gmsstrm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/gmsstrm.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/gmsstrm.cpp.i
.PHONY : src/gmsstrm.cpp.i

src/gmsstrm.s: src/gmsstrm.cpp.s
.PHONY : src/gmsstrm.s

# target to generate assembly for a file
src/gmsstrm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/src/gmsstrm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/gmsstrm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/gmsstrm.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/gmsstrm.cpp.s
.PHONY : src/gmsstrm.cpp.s

src/gxfile.o: src/gxfile.cpp.o
.PHONY : src/gxfile.o

# target to build an object file
src/gxfile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/src/gxfile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/gxfile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/gxfile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/gxfile.cpp.o
.PHONY : src/gxfile.cpp.o

src/gxfile.i: src/gxfile.cpp.i
.PHONY : src/gxfile.i

# target to preprocess a source file
src/gxfile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/src/gxfile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/gxfile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/gxfile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/gxfile.cpp.i
.PHONY : src/gxfile.cpp.i

src/gxfile.s: src/gxfile.cpp.s
.PHONY : src/gxfile.s

# target to generate assembly for a file
src/gxfile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/src/gxfile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/gxfile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/gxfile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/gxfile.cpp.s
.PHONY : src/gxfile.cpp.s

src/tests/datastoragetests.o: src/tests/datastoragetests.cpp.o
.PHONY : src/tests/datastoragetests.o

# target to build an object file
src/tests/datastoragetests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/datastoragetests.cpp.o
.PHONY : src/tests/datastoragetests.cpp.o

src/tests/datastoragetests.i: src/tests/datastoragetests.cpp.i
.PHONY : src/tests/datastoragetests.i

# target to preprocess a source file
src/tests/datastoragetests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/datastoragetests.cpp.i
.PHONY : src/tests/datastoragetests.cpp.i

src/tests/datastoragetests.s: src/tests/datastoragetests.cpp.s
.PHONY : src/tests/datastoragetests.s

# target to generate assembly for a file
src/tests/datastoragetests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/datastoragetests.cpp.s
.PHONY : src/tests/datastoragetests.cpp.s

src/tests/doctestmain.o: src/tests/doctestmain.cpp.o
.PHONY : src/tests/doctestmain.o

# target to build an object file
src/tests/doctestmain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/doctestmain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxwraptest.dir/build.make CMakeFiles/gdxwraptest.dir/src/tests/doctestmain.cpp.o
.PHONY : src/tests/doctestmain.cpp.o

src/tests/doctestmain.i: src/tests/doctestmain.cpp.i
.PHONY : src/tests/doctestmain.i

# target to preprocess a source file
src/tests/doctestmain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/doctestmain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxwraptest.dir/build.make CMakeFiles/gdxwraptest.dir/src/tests/doctestmain.cpp.i
.PHONY : src/tests/doctestmain.cpp.i

src/tests/doctestmain.s: src/tests/doctestmain.cpp.s
.PHONY : src/tests/doctestmain.s

# target to generate assembly for a file
src/tests/doctestmain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/doctestmain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxwraptest.dir/build.make CMakeFiles/gdxwraptest.dir/src/tests/doctestmain.cpp.s
.PHONY : src/tests/doctestmain.cpp.s

src/tests/gdxtests.o: src/tests/gdxtests.cpp.o
.PHONY : src/tests/gdxtests.o

# target to build an object file
src/tests/gdxtests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gdxtests.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxwraptest.dir/build.make CMakeFiles/gdxwraptest.dir/src/tests/gdxtests.cpp.o
.PHONY : src/tests/gdxtests.cpp.o

src/tests/gdxtests.i: src/tests/gdxtests.cpp.i
.PHONY : src/tests/gdxtests.i

# target to preprocess a source file
src/tests/gdxtests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gdxtests.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxwraptest.dir/build.make CMakeFiles/gdxwraptest.dir/src/tests/gdxtests.cpp.i
.PHONY : src/tests/gdxtests.cpp.i

src/tests/gdxtests.s: src/tests/gdxtests.cpp.s
.PHONY : src/tests/gdxtests.s

# target to generate assembly for a file
src/tests/gdxtests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gdxtests.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxwraptest.dir/build.make CMakeFiles/gdxwraptest.dir/src/tests/gdxtests.cpp.s
.PHONY : src/tests/gdxtests.cpp.s

src/tests/gmsdatatests.o: src/tests/gmsdatatests.cpp.o
.PHONY : src/tests/gmsdatatests.o

# target to build an object file
src/tests/gmsdatatests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gmsdatatests.cpp.o
.PHONY : src/tests/gmsdatatests.cpp.o

src/tests/gmsdatatests.i: src/tests/gmsdatatests.cpp.i
.PHONY : src/tests/gmsdatatests.i

# target to preprocess a source file
src/tests/gmsdatatests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gmsdatatests.cpp.i
.PHONY : src/tests/gmsdatatests.cpp.i

src/tests/gmsdatatests.s: src/tests/gmsdatatests.cpp.s
.PHONY : src/tests/gmsdatatests.s

# target to generate assembly for a file
src/tests/gmsdatatests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gmsdatatests.cpp.s
.PHONY : src/tests/gmsdatatests.cpp.s

src/tests/gmsobjtests.o: src/tests/gmsobjtests.cpp.o
.PHONY : src/tests/gmsobjtests.o

# target to build an object file
src/tests/gmsobjtests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gmsobjtests.cpp.o
.PHONY : src/tests/gmsobjtests.cpp.o

src/tests/gmsobjtests.i: src/tests/gmsobjtests.cpp.i
.PHONY : src/tests/gmsobjtests.i

# target to preprocess a source file
src/tests/gmsobjtests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gmsobjtests.cpp.i
.PHONY : src/tests/gmsobjtests.cpp.i

src/tests/gmsobjtests.s: src/tests/gmsobjtests.cpp.s
.PHONY : src/tests/gmsobjtests.s

# target to generate assembly for a file
src/tests/gmsobjtests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gmsobjtests.cpp.s
.PHONY : src/tests/gmsobjtests.cpp.s

src/tests/gxfiletests.o: src/tests/gxfiletests.cpp.o
.PHONY : src/tests/gxfiletests.o

# target to build an object file
src/tests/gxfiletests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gxfiletests.cpp.o
.PHONY : src/tests/gxfiletests.cpp.o

src/tests/gxfiletests.i: src/tests/gxfiletests.cpp.i
.PHONY : src/tests/gxfiletests.i

# target to preprocess a source file
src/tests/gxfiletests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gxfiletests.cpp.i
.PHONY : src/tests/gxfiletests.cpp.i

src/tests/gxfiletests.s: src/tests/gxfiletests.cpp.s
.PHONY : src/tests/gxfiletests.s

# target to generate assembly for a file
src/tests/gxfiletests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/gxfiletests.cpp.s
.PHONY : src/tests/gxfiletests.cpp.s

src/tests/strhashtests.o: src/tests/strhashtests.cpp.o
.PHONY : src/tests/strhashtests.o

# target to build an object file
src/tests/strhashtests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/strhashtests.cpp.o
.PHONY : src/tests/strhashtests.cpp.o

src/tests/strhashtests.i: src/tests/strhashtests.cpp.i
.PHONY : src/tests/strhashtests.i

# target to preprocess a source file
src/tests/strhashtests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/strhashtests.cpp.i
.PHONY : src/tests/strhashtests.cpp.i

src/tests/strhashtests.s: src/tests/strhashtests.cpp.s
.PHONY : src/tests/strhashtests.s

# target to generate assembly for a file
src/tests/strhashtests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/strhashtests.cpp.s
.PHONY : src/tests/strhashtests.cpp.s

src/tests/utilstests.o: src/tests/utilstests.cpp.o
.PHONY : src/tests/utilstests.o

# target to build an object file
src/tests/utilstests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/utilstests.cpp.o
.PHONY : src/tests/utilstests.cpp.o

src/tests/utilstests.i: src/tests/utilstests.cpp.i
.PHONY : src/tests/utilstests.i

# target to preprocess a source file
src/tests/utilstests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/utilstests.cpp.i
.PHONY : src/tests/utilstests.cpp.i

src/tests/utilstests.s: src/tests/utilstests.cpp.s
.PHONY : src/tests/utilstests.s

# target to generate assembly for a file
src/tests/utilstests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/tests/utilstests.cpp.s
.PHONY : src/tests/utilstests.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/src/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/src/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/src/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/src/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/src/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

zlib/adler32.o: zlib/adler32.c.o
.PHONY : zlib/adler32.o

# target to build an object file
zlib/adler32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/adler32.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/adler32.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/adler32.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/adler32.c.o
.PHONY : zlib/adler32.c.o

zlib/adler32.i: zlib/adler32.c.i
.PHONY : zlib/adler32.i

# target to preprocess a source file
zlib/adler32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/adler32.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/adler32.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/adler32.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/adler32.c.i
.PHONY : zlib/adler32.c.i

zlib/adler32.s: zlib/adler32.c.s
.PHONY : zlib/adler32.s

# target to generate assembly for a file
zlib/adler32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/adler32.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/adler32.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/adler32.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/adler32.c.s
.PHONY : zlib/adler32.c.s

zlib/compress.o: zlib/compress.c.o
.PHONY : zlib/compress.o

# target to build an object file
zlib/compress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/compress.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/compress.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/compress.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/compress.c.o
.PHONY : zlib/compress.c.o

zlib/compress.i: zlib/compress.c.i
.PHONY : zlib/compress.i

# target to preprocess a source file
zlib/compress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/compress.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/compress.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/compress.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/compress.c.i
.PHONY : zlib/compress.c.i

zlib/compress.s: zlib/compress.c.s
.PHONY : zlib/compress.s

# target to generate assembly for a file
zlib/compress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/compress.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/compress.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/compress.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/compress.c.s
.PHONY : zlib/compress.c.s

zlib/crc32.o: zlib/crc32.c.o
.PHONY : zlib/crc32.o

# target to build an object file
zlib/crc32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/crc32.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/crc32.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/crc32.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/crc32.c.o
.PHONY : zlib/crc32.c.o

zlib/crc32.i: zlib/crc32.c.i
.PHONY : zlib/crc32.i

# target to preprocess a source file
zlib/crc32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/crc32.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/crc32.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/crc32.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/crc32.c.i
.PHONY : zlib/crc32.c.i

zlib/crc32.s: zlib/crc32.c.s
.PHONY : zlib/crc32.s

# target to generate assembly for a file
zlib/crc32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/crc32.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/crc32.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/crc32.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/crc32.c.s
.PHONY : zlib/crc32.c.s

zlib/deflate.o: zlib/deflate.c.o
.PHONY : zlib/deflate.o

# target to build an object file
zlib/deflate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/deflate.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/deflate.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/deflate.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/deflate.c.o
.PHONY : zlib/deflate.c.o

zlib/deflate.i: zlib/deflate.c.i
.PHONY : zlib/deflate.i

# target to preprocess a source file
zlib/deflate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/deflate.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/deflate.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/deflate.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/deflate.c.i
.PHONY : zlib/deflate.c.i

zlib/deflate.s: zlib/deflate.c.s
.PHONY : zlib/deflate.s

# target to generate assembly for a file
zlib/deflate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/deflate.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/deflate.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/deflate.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/deflate.c.s
.PHONY : zlib/deflate.c.s

zlib/gzclose.o: zlib/gzclose.c.o
.PHONY : zlib/gzclose.o

# target to build an object file
zlib/gzclose.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzclose.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzclose.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzclose.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzclose.c.o
.PHONY : zlib/gzclose.c.o

zlib/gzclose.i: zlib/gzclose.c.i
.PHONY : zlib/gzclose.i

# target to preprocess a source file
zlib/gzclose.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzclose.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzclose.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzclose.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzclose.c.i
.PHONY : zlib/gzclose.c.i

zlib/gzclose.s: zlib/gzclose.c.s
.PHONY : zlib/gzclose.s

# target to generate assembly for a file
zlib/gzclose.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzclose.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzclose.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzclose.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzclose.c.s
.PHONY : zlib/gzclose.c.s

zlib/gzlib.o: zlib/gzlib.c.o
.PHONY : zlib/gzlib.o

# target to build an object file
zlib/gzlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzlib.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzlib.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzlib.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzlib.c.o
.PHONY : zlib/gzlib.c.o

zlib/gzlib.i: zlib/gzlib.c.i
.PHONY : zlib/gzlib.i

# target to preprocess a source file
zlib/gzlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzlib.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzlib.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzlib.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzlib.c.i
.PHONY : zlib/gzlib.c.i

zlib/gzlib.s: zlib/gzlib.c.s
.PHONY : zlib/gzlib.s

# target to generate assembly for a file
zlib/gzlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzlib.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzlib.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzlib.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzlib.c.s
.PHONY : zlib/gzlib.c.s

zlib/gzread.o: zlib/gzread.c.o
.PHONY : zlib/gzread.o

# target to build an object file
zlib/gzread.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzread.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzread.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzread.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzread.c.o
.PHONY : zlib/gzread.c.o

zlib/gzread.i: zlib/gzread.c.i
.PHONY : zlib/gzread.i

# target to preprocess a source file
zlib/gzread.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzread.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzread.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzread.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzread.c.i
.PHONY : zlib/gzread.c.i

zlib/gzread.s: zlib/gzread.c.s
.PHONY : zlib/gzread.s

# target to generate assembly for a file
zlib/gzread.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzread.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzread.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzread.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzread.c.s
.PHONY : zlib/gzread.c.s

zlib/gzwrite.o: zlib/gzwrite.c.o
.PHONY : zlib/gzwrite.o

# target to build an object file
zlib/gzwrite.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzwrite.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzwrite.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzwrite.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzwrite.c.o
.PHONY : zlib/gzwrite.c.o

zlib/gzwrite.i: zlib/gzwrite.c.i
.PHONY : zlib/gzwrite.i

# target to preprocess a source file
zlib/gzwrite.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzwrite.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzwrite.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzwrite.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzwrite.c.i
.PHONY : zlib/gzwrite.c.i

zlib/gzwrite.s: zlib/gzwrite.c.s
.PHONY : zlib/gzwrite.s

# target to generate assembly for a file
zlib/gzwrite.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/gzwrite.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/gzwrite.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/gzwrite.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/gzwrite.c.s
.PHONY : zlib/gzwrite.c.s

zlib/infback.o: zlib/infback.c.o
.PHONY : zlib/infback.o

# target to build an object file
zlib/infback.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/infback.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/infback.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/infback.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/infback.c.o
.PHONY : zlib/infback.c.o

zlib/infback.i: zlib/infback.c.i
.PHONY : zlib/infback.i

# target to preprocess a source file
zlib/infback.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/infback.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/infback.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/infback.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/infback.c.i
.PHONY : zlib/infback.c.i

zlib/infback.s: zlib/infback.c.s
.PHONY : zlib/infback.s

# target to generate assembly for a file
zlib/infback.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/infback.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/infback.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/infback.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/infback.c.s
.PHONY : zlib/infback.c.s

zlib/inffast.o: zlib/inffast.c.o
.PHONY : zlib/inffast.o

# target to build an object file
zlib/inffast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/inffast.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/inffast.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/inffast.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/inffast.c.o
.PHONY : zlib/inffast.c.o

zlib/inffast.i: zlib/inffast.c.i
.PHONY : zlib/inffast.i

# target to preprocess a source file
zlib/inffast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/inffast.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/inffast.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/inffast.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/inffast.c.i
.PHONY : zlib/inffast.c.i

zlib/inffast.s: zlib/inffast.c.s
.PHONY : zlib/inffast.s

# target to generate assembly for a file
zlib/inffast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/inffast.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/inffast.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/inffast.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/inffast.c.s
.PHONY : zlib/inffast.c.s

zlib/inflate.o: zlib/inflate.c.o
.PHONY : zlib/inflate.o

# target to build an object file
zlib/inflate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/inflate.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/inflate.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/inflate.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/inflate.c.o
.PHONY : zlib/inflate.c.o

zlib/inflate.i: zlib/inflate.c.i
.PHONY : zlib/inflate.i

# target to preprocess a source file
zlib/inflate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/inflate.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/inflate.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/inflate.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/inflate.c.i
.PHONY : zlib/inflate.c.i

zlib/inflate.s: zlib/inflate.c.s
.PHONY : zlib/inflate.s

# target to generate assembly for a file
zlib/inflate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/inflate.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/inflate.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/inflate.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/inflate.c.s
.PHONY : zlib/inflate.c.s

zlib/inftrees.o: zlib/inftrees.c.o
.PHONY : zlib/inftrees.o

# target to build an object file
zlib/inftrees.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/inftrees.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/inftrees.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/inftrees.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/inftrees.c.o
.PHONY : zlib/inftrees.c.o

zlib/inftrees.i: zlib/inftrees.c.i
.PHONY : zlib/inftrees.i

# target to preprocess a source file
zlib/inftrees.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/inftrees.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/inftrees.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/inftrees.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/inftrees.c.i
.PHONY : zlib/inftrees.c.i

zlib/inftrees.s: zlib/inftrees.c.s
.PHONY : zlib/inftrees.s

# target to generate assembly for a file
zlib/inftrees.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/inftrees.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/inftrees.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/inftrees.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/inftrees.c.s
.PHONY : zlib/inftrees.c.s

zlib/trees.o: zlib/trees.c.o
.PHONY : zlib/trees.o

# target to build an object file
zlib/trees.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/trees.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/trees.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/trees.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/trees.c.o
.PHONY : zlib/trees.c.o

zlib/trees.i: zlib/trees.c.i
.PHONY : zlib/trees.i

# target to preprocess a source file
zlib/trees.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/trees.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/trees.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/trees.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/trees.c.i
.PHONY : zlib/trees.c.i

zlib/trees.s: zlib/trees.c.s
.PHONY : zlib/trees.s

# target to generate assembly for a file
zlib/trees.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/trees.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/trees.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/trees.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/trees.c.s
.PHONY : zlib/trees.c.s

zlib/uncompr.o: zlib/uncompr.c.o
.PHONY : zlib/uncompr.o

# target to build an object file
zlib/uncompr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/uncompr.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/uncompr.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/uncompr.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/uncompr.c.o
.PHONY : zlib/uncompr.c.o

zlib/uncompr.i: zlib/uncompr.c.i
.PHONY : zlib/uncompr.i

# target to preprocess a source file
zlib/uncompr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/uncompr.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/uncompr.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/uncompr.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/uncompr.c.i
.PHONY : zlib/uncompr.c.i

zlib/uncompr.s: zlib/uncompr.c.s
.PHONY : zlib/uncompr.s

# target to generate assembly for a file
zlib/uncompr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/uncompr.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/uncompr.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/uncompr.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/uncompr.c.s
.PHONY : zlib/uncompr.c.s

zlib/zutil.o: zlib/zutil.c.o
.PHONY : zlib/zutil.o

# target to build an object file
zlib/zutil.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/zutil.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/zutil.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/zutil.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/zutil.c.o
.PHONY : zlib/zutil.c.o

zlib/zutil.i: zlib/zutil.c.i
.PHONY : zlib/zutil.i

# target to preprocess a source file
zlib/zutil.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/zutil.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/zutil.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/zutil.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/zutil.c.i
.PHONY : zlib/zutil.c.i

zlib/zutil.s: zlib/zutil.c.s
.PHONY : zlib/zutil.s

# target to generate assembly for a file
zlib/zutil.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxcclib64.dir/build.make CMakeFiles/gdxcclib64.dir/zlib/zutil.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gdxtest.dir/build.make CMakeFiles/gdxtest.dir/zlib/zutil.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example1.dir/build.make CMakeFiles/xp_example1.dir/zlib/zutil.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xp_example2.dir/build.make CMakeFiles/xp_example2.dir/zlib/zutil.c.s
.PHONY : zlib/zutil.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gdxcclib64"
	@echo "... gdxtest"
	@echo "... gdxwraptest"
	@echo "... xp_example1"
	@echo "... xp_example2"
	@echo "... generated/gdxcc.o"
	@echo "... generated/gdxcc.i"
	@echo "... generated/gdxcc.s"
	@echo "... generated/gdxcclib.o"
	@echo "... generated/gdxcclib.i"
	@echo "... generated/gdxcclib.s"
	@echo "... generated/optcc.o"
	@echo "... generated/optcc.i"
	@echo "... generated/optcc.s"
	@echo "... src/examples/xp_example1.o"
	@echo "... src/examples/xp_example1.i"
	@echo "... src/examples/xp_example1.s"
	@echo "... src/examples/xp_example2.o"
	@echo "... src/examples/xp_example2.i"
	@echo "... src/examples/xp_example2.s"
	@echo "... src/gmsstrm.o"
	@echo "... src/gmsstrm.i"
	@echo "... src/gmsstrm.s"
	@echo "... src/gxfile.o"
	@echo "... src/gxfile.i"
	@echo "... src/gxfile.s"
	@echo "... src/tests/datastoragetests.o"
	@echo "... src/tests/datastoragetests.i"
	@echo "... src/tests/datastoragetests.s"
	@echo "... src/tests/doctestmain.o"
	@echo "... src/tests/doctestmain.i"
	@echo "... src/tests/doctestmain.s"
	@echo "... src/tests/gdxtests.o"
	@echo "... src/tests/gdxtests.i"
	@echo "... src/tests/gdxtests.s"
	@echo "... src/tests/gmsdatatests.o"
	@echo "... src/tests/gmsdatatests.i"
	@echo "... src/tests/gmsdatatests.s"
	@echo "... src/tests/gmsobjtests.o"
	@echo "... src/tests/gmsobjtests.i"
	@echo "... src/tests/gmsobjtests.s"
	@echo "... src/tests/gxfiletests.o"
	@echo "... src/tests/gxfiletests.i"
	@echo "... src/tests/gxfiletests.s"
	@echo "... src/tests/strhashtests.o"
	@echo "... src/tests/strhashtests.i"
	@echo "... src/tests/strhashtests.s"
	@echo "... src/tests/utilstests.o"
	@echo "... src/tests/utilstests.i"
	@echo "... src/tests/utilstests.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... zlib/adler32.o"
	@echo "... zlib/adler32.i"
	@echo "... zlib/adler32.s"
	@echo "... zlib/compress.o"
	@echo "... zlib/compress.i"
	@echo "... zlib/compress.s"
	@echo "... zlib/crc32.o"
	@echo "... zlib/crc32.i"
	@echo "... zlib/crc32.s"
	@echo "... zlib/deflate.o"
	@echo "... zlib/deflate.i"
	@echo "... zlib/deflate.s"
	@echo "... zlib/gzclose.o"
	@echo "... zlib/gzclose.i"
	@echo "... zlib/gzclose.s"
	@echo "... zlib/gzlib.o"
	@echo "... zlib/gzlib.i"
	@echo "... zlib/gzlib.s"
	@echo "... zlib/gzread.o"
	@echo "... zlib/gzread.i"
	@echo "... zlib/gzread.s"
	@echo "... zlib/gzwrite.o"
	@echo "... zlib/gzwrite.i"
	@echo "... zlib/gzwrite.s"
	@echo "... zlib/infback.o"
	@echo "... zlib/infback.i"
	@echo "... zlib/infback.s"
	@echo "... zlib/inffast.o"
	@echo "... zlib/inffast.i"
	@echo "... zlib/inffast.s"
	@echo "... zlib/inflate.o"
	@echo "... zlib/inflate.i"
	@echo "... zlib/inflate.s"
	@echo "... zlib/inftrees.o"
	@echo "... zlib/inftrees.i"
	@echo "... zlib/inftrees.s"
	@echo "... zlib/trees.o"
	@echo "... zlib/trees.i"
	@echo "... zlib/trees.s"
	@echo "... zlib/uncompr.o"
	@echo "... zlib/uncompr.i"
	@echo "... zlib/uncompr.s"
	@echo "... zlib/zutil.o"
	@echo "... zlib/zutil.i"
	@echo "... zlib/zutil.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

